### ISSUE TITLE
minVersion

### ISSUE THREAD

**Issue by singa76** [nhaarman/Triad#106]
hi, 
Thanks for the great library.
I am trying to re-architect my app around Triad, but the minimum android sdk versions seems to be set to 16 at the moment, which means that to use Triad, I would have to get existing users with older versions of android.

Can I check if there are any plans to make the min sdk version lower?

**Comment by nhaarman** [comment]
The library uses some API's that require level 16. Also, if you target 16+ you target 98% of the devices at the moment.
